In [ ]:
import numpy as np
a =np.array([[1,2],[3,4],[5,6]])
b =np.array([[1,2,3],[4,5,6],[7,8,9]])
c =np.array([[1,2,3],[4,5,6],[7,8,9]])
d =np.array([5,6,7])
#print(a+b)

print(b+c)
print("\n",b*c)
print("\n",b*d)
print("\n",b*10)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]

 [[ 5 12 21]
 [20 30 42]
 [35 48 63]]
