In [13]:
import numpy as np

In [30]:
arr=np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


### YO!

In [ ]:
salary=np.array([[30000,5000,2000],[22000,4000,1500],[45000,4500,1800]])
print(salary)
print(np.shape(salary))
print(np.size(salary))
print(np.ndim(salary))
print("Sum:",np.sum(salary))
print("Mean:",np.mean(salary))
print("Median:",np.median(salary))
print("Standard Deviation:",np.std(salary))
print("Variance:",np.var(salary))
print("Minimum:",np.min(salary))
print("Maximum:",np.max(salary))
print("Index of Minimum:",np.argmin(salary))
print("Index of Maximum:",np.argmax(salary))
print("Unique Values:",np.unique(salary))
print("Sorted Array:",np.sort(salary, axis=None))
print("Transposed Array:",np.transpose(salary))
print("Sum of each column:",np.sum(salary, axis=0))  # Sum of each column
print("Sum of each row:",np.sum(salary, axis=1))  # Sum of each row


In [38]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("Original Array:\n", a)
print("First row, first two columns:",a[0,0:2])  # First row, first two columns
print("Second row all column:",a[1,0:3])  # Second row, all columns
print("All row, first column:",a[0:3,0])  # All rows, first column
print("All row, last column:",a[0:3,2])  # All rows, last column
print("Last row, all column:",a[2,0:3])  # Last row, all columns

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row, first two columns: [1 2]
Second row all column: [4 5 6]
All row, first column: [1 4 7]
All row, last column: [3 6 9]
Last row, all column: [7 8 9]
