In [81]:
import numpy as np
#import matplotlib.pyplot as plt

In [82]:
marks = np.array([[101,78,89,59,67],[102,78,87,56,63],[103,65,98,76,78]])
print(marks)

print("\nMaths marks\n",marks [:,1:2])

marks[:,1:5]=marks[:,1:5]+5
print("\nAdd 5 \n",marks)

avg = np.mean(marks[:,1:5],axis=1)
print("\nAverage marks\n",avg)

# print(marks[1:1])

[[101  78  89  59  67]
 [102  78  87  56  63]
 [103  65  98  76  78]]

Maths marks
 [[78]
 [78]
 [65]]

Add 5 
 [[101  83  94  64  72]
 [102  83  92  61  68]
 [103  70 103  81  83]]

Average marks
 [78.25 76.   84.25]
