In [15]:
import numpy as np

In [ ]:
# matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(matrix)
# col_sum=np.sum(matrix,axis=0)
# print(col_sum)

# arr=np.array([[101, 75, 80, 85],
#               [102, 65, 70, 60],
#               [103, 90, 88, 92],
#               [104, 55, 60, 58],
#               [105, 78, 82, 80]])

math=arr[:,1]
print("Math scores:", math)
avg=np.mean(arr[:,1:],axis=1)
print("Average scores:", avg)
up=arr.copy()
up[:,1:]=arr[:,1:]+5
print("Updated scores:\n", up)
passed=arr[:,1:]>=60
print("Passed subjects:\n", passed)

Math scores: [75 65 90 55 78]
Average scores: [80.         65.         90.         57.66666667 80.        ]
Updated scores:
 [[101  80  85  90]
 [102  70  75  65]
 [103  95  93  97]
 [104  60  65  63]
 [105  83  87  85]]
Passed subjects:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [False  True False]
 [ True  True  True]]
