In [1]:
import numpy as np


In [2]:
arr=np.array([1,2,3,4,5])
print(arr)
write=np.savetxt('arr.txt',arr,fmt='%d')
read=np.loadtxt('arr.txt')
print(read)

csv=np.array([5,6,7,8,9])
np.savetxt('csv.csv',csv,delimiter=',',fmt='%d')
csv_read=np.loadtxt('csv.csv',delimiter=',')
print(csv_read)

arr2=np.array([9,8,np.nan,6,5])
print(arr2)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[5. 6. 7. 8. 9.]
[ 9.  8. nan  6.  5.]
